name: Price Action Analysis

on:
  schedule:
    # Kompletní analýza jednou denně ráno v 7:30 UTC (pracovní dny)
    - cron: '30 7 * * 1-5'
    
    # Intraday analýza každé 2 hodiny od 9:30 do 21:30 UTC (pracovní dny) 
    - cron: '30 9,11,13,15,17,19,21 * * 1-5'
  
  workflow_dispatch:
    inputs:
      symbol:
        description: 'Trading pár (např. BTCUSDT)'
        required: true
        default: 'BTCUSDT'
      analysis_type:
        description: 'Typ analýzy'
        required: true
        default: 'complete'
        type: choice
        options:
          - complete
          - intraday
          - single
      interval:
        description: 'Časový interval (pouze pro single-timeframe)'
        required: false
        default: '30m'
        type: choice
        options:
          - 1m
          - 5m
          - 15m
          - 30m
          - 1h
          - 4h
          - 1d
          - 1w
      days:
        description: 'Počet dní historie (pouze pro single-timeframe)'
        required: false
        default: '5'
        type: number

jobs:
  analyze:
    runs-on: ubuntu-latest
    # Explicitně specifikovat použití prostředí "prod" pro přístup k environment secrets
    environment: prod
    
    # Definice proměnných prostředí přímo na úrovni jobu
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    
    steps:
      - name: Checkout kódu
        uses: actions/checkout@v3
      
      - name: Nastavení Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Instalace závislostí
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Ověření proměnných prostředí
      - name: Kontrola proměnných prostředí
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "CHYBA: OPENAI_API_KEY není nastaveno"
            exit 1
          fi
          if [ -z "$TELEGRAM_TOKEN" ]; then
            echo "CHYBA: TELEGRAM_TOKEN není nastaveno"
            exit 1
          fi
          if [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "CHYBA: TELEGRAM_CHAT_ID není nastaveno"
            exit 1
          fi
          echo "✅ Všechny potřebné proměnné prostředí jsou nastaveny"
          
      - name: Určení typu analýzy
        id: analysis-type
        run: |
          HOUR=$(date +%H)
          if [[ $GITHUB_EVENT_NAME == 'schedule' ]]; then
            if [[ $HOUR == "07" ]]; then
              echo "type=complete" >> $GITHUB_OUTPUT
            else
              echo "type=intraday" >> $GITHUB_OUTPUT
            fi
          elif [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then
            echo "type=${{ github.event.inputs.analysis_type }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Spuštění kompletní analýzy
        if: steps.analysis-type.outputs.type == 'complete'
        run: |
          # Kompletní analýza pro BTC
          python main.py -s BTCUSDT --complete
          sleep 60
          
          # Kompletní analýza pro ETH
          python main.py -s ETHUSDT --complete
      
      - name: Spuštění intraday analýzy
        if: steps.analysis-type.outputs.type == 'intraday'
        run: |
          # Intraday analýza pro BTC
          python main.py -s BTCUSDT --intraday
          sleep 60
          
          # Intraday analýza pro ETH
          python main.py -s ETHUSDT --intraday
      
      - name: Spuštění single-timeframe analýzy
        if: steps.analysis-type.outputs.type == 'single'
        run: |
          python main.py -s ${{ github.event.inputs.symbol }} -i ${{ github.event.inputs.interval }} -d ${{ github.event.inputs.days }}
      
      - name: Artefakty - ukládání CSV
        uses: actions/upload-artifact@v4
        with:
          name: analysis-data
          path: PA_*.csv
          retention-days: 5
