name: Multi-Timeframe Price Action Analysis

on:
  schedule:
    # Spouštění multi-timeframe analýzy v klíčových časech
    - cron: '30 1,7,13,19 * * 1-5'  # 1:30, 7:30, 13:30, 19:30 UTC v pracovní dny
  
  # Umožňuje ruční spuštění z GitHub UI
  workflow_dispatch:
    inputs:
      symbol:
        description: 'Trading pár (např. BTCUSDT)'
        required: true
        default: 'BTCUSDT'
      analysis_type:
        description: 'Typ analýzy'
        required: true
        default: 'multi'
        type: choice
        options:
          - multi
          - single
      interval:
        description: 'Časový interval (pouze pro single-timeframe)'
        required: false
        default: '30m'
        type: choice
        options:
          - 1m
          - 5m
          - 15m
          - 30m
          - 1h
          - 4h
          - 1d
          - 1w
      days:
        description: 'Počet dní historie (pouze pro single-timeframe)'
        required: false
        default: '5'
        type: number

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout kódu
        uses: actions/checkout@v3
      
      - name: Nastavení Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Instalace závislostí
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Spuštění multi-timeframe analýzy - plánovaná
        if: github.event_name == 'schedule'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Multi-timeframe analýza pro BTC
          python main.py -s BTCUSDT --multi
          sleep 60  # Delší pauza mezi analýzami (kvůli API limitům)
          
          # Multi-timeframe analýza pro ETH
          python main.py -s ETHUSDT --multi
      
      - name: Spuštění analýzy - manuální
        if: github.event_name == 'workflow_dispatch'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ "${{ github.event.inputs.analysis_type }}" == "multi" ]; then
            python main.py -s ${{ github.event.inputs.symbol }} --multi
          else
            python main.py -s ${{ github.event.inputs.symbol }} -i ${{ github.event.inputs.interval }} -d ${{ github.event.inputs.days }}
          fi
      
      - name: Artefakty - ukládání CSV
        uses: actions/upload-artifact@v3
        with:
          name: analysis-data
          path: PA_*.csv
          retention-days: 5
